// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * - THEME_SYSTEM: 跟随系统
 * - THEME_LIGHT: 日间模式
 * - THEME_DARK: 夜间模式
 */
export type AppearanceSettingsTheme = 'THEME_SYSTEM' | 'THEME_LIGHT' | 'THEME_DARK';

/**
 * 发评论
 */
export type CommentServiceCreateCommentBody = {
    content?: string;
    /**
     * 如果是回复一级评论或二级评论，需要填这些
     * 回复帖子(一级评论)时：root_id="", parent_id=""
     * 回复评论(二级评论)时：root_id="一级评论ID", parent_id="被回复的评论ID"
     */
    root_id?: string;
    /**
     * reply_to_user_id 可以由后端根据 parent_id 查出来，不需要前端传，防篡改
     */
    parent_id?: string;
};

export type GovernanceServiceResolveReportBody = {
    action?: ResolveReportRequestAction;
    /**
     * 处理备注
     */
    note?: string;
};

/**
 * 来源标记
 *
 * - SOURCE_COMMUNITY: 社区帖子
 * - SOURCE_OFFICIAL: 官方公告
 * - SOURCE_EXTERNAL: 外部爬取的红书/B站动态
 */
export type HomeTrendingItemSource = 'SOURCE_COMMUNITY' | 'SOURCE_OFFICIAL' | 'SOURCE_EXTERNAL';

/**
 * 收藏
 */
export type InteractionServiceSetCollectBody = {
    is_active?: boolean;
};

/**
 * 点赞
 */
export type InteractionServiceSetLikeBody = {
    type?: TargetType;
    /**
     * true=点赞, false=取消
     */
    is_active?: boolean;
};

/**
 * 排序：热门/最新 (通常子评论默认按时间正序，一级评论按热度)
 *
 * - SORT_HOT: 热度 (点赞+回复权重)
 * - SORT_NEW: 最新 (时间倒序)
 * - SORT_OLD: 最早 (时间正序，常用于楼中楼)
 */
export type ListCommentsRequestSort = 'SORT_UNSPECIFIED' | 'SORT_HOT' | 'SORT_NEW' | 'SORT_OLD';

export type ListMinistersResponseYearGroup = {
    year?: number;
    /**
     * 第几届
     */
    session_number?: number;
    ministers?: Array<Minister>;
};

/**
 * - RELATION_TYPE_FOLLOWING: 关注的人
 * - RELATION_TYPE_FOLLOWERS: 粉丝
 * - RELATION_TYPE_MUTUAL_FOLLOWERS: 互相关注
 */
export type ListRelationshipsRequestRelationType = 'RELATION_TYPE_FOLLOWING' | 'RELATION_TYPE_FOLLOWERS' | 'RELATION_TYPE_MUTUAL_FOLLOWERS';

/**
 * 范围：全部已读 | 指定分类已读 | 指定单条已读
 */
export type MarkReadRequestScope = 'SCOPE_ALL' | 'SCOPE_CATEGORY' | 'SCOPE_ID';

/**
 * 裁决动作
 *
 * - ACTION_IGNORE: 忽略/无违规
 * - ACTION_DELETE_CONTENT: 删除内容
 * - ACTION_BAN_USER: 封禁用户 (通常需调用 UserAdminService)
 */
export type ResolveReportRequestAction = 'ACTION_IGNORE' | 'ACTION_DELETE_CONTENT' | 'ACTION_BAN_USER';

/**
 * 审核认证申请请求
 */
export type UserAdminServiceApproveVerificationBody = {
    /**
     * true=通过, false=驳回
     */
    approve?: boolean;
    /**
     * 驳回原因 (仅当 approve 为 false 时需要)
     */
    reject_reason?: string;
};

/**
 * 统一关注操作
 */
export type UserServiceSetFollowBody = {
    /**
     * true=关注, false=取关
     */
    is_active?: boolean;
};

export type ProtobufAny = {
    '@type'?: string;
    [key: string]: unknown | string | undefined;
};

export type RpcStatus = {
    code?: number;
    message?: string;
    details?: Array<ProtobufAny>;
};

/**
 * 活动
 */
export type Activity = {
    id?: string;
    name?: string;
    name_en?: string;
    cover_image?: string;
    /**
     * B站或红书视频链接
     */
    intro_video_url?: string;
    description?: string;
    /**
     * 建议用 int64 时间戳
     */
    start_time?: string;
    end_time?: string;
    links?: Array<Link>;
    sort_order?: number;
};

/**
 * 外观设置
 */
export type AppearanceSettings = {
    theme?: AppearanceSettingsTheme;
};

export type ApplyVerificationRequest = {
    /**
     * 申请的认证头衔 (如: 23届部长, 社团负责人)
     */
    verified_title?: string;
};

export type ApplyVerificationResponse = {
    [key: string]: unknown;
};

/**
 * 审核认证申请响应
 */
export type ApproveVerificationResponse = {
    succeed?: boolean;
    message?: string;
};

export type BanItem = {
    /**
     * 相关的举报 ID
     */
    report_id?: string;
    status?: BanStatus;
};

export type BanRequest = {
    ban_items?: Array<BanItem>;
};

export type BanResponse = {
    [key: string]: unknown;
};

/**
 * - BAN_STATUS_BAN: 封禁/删除
 * - BAN_STATUS_UNBAN: 解封/恢复
 */
export type BanStatus = 'BAN_STATUS_UNSPECIFIED' | 'BAN_STATUS_BAN' | 'BAN_STATUS_UNBAN';

export type BasePrivacyLevel = 'BASE_PRIVACY_LEVEL_PUBLIC' | 'BASE_PRIVACY_LEVEL_PRIVATE';

export type ChatPrivacyLevel = 'CHAT_PRIVACY_LEVEL_PUBLIC' | 'CHAT_PRIVACY_LEVEL_FOLLOWERS' | 'CHAT_PRIVACY_LEVEL_MUTUAL' | 'CHAT_PRIVACY_LEVEL_PRIVATE';

export type Comment = {
    comment_id?: string;
    author?: UserSummary;
    content?: string;
    /**
     * 关联关系
     *
     * 所属帖子ID
     */
    post_id?: string;
    /**
     * 所属根评论ID (如果是1级评论，此字段为空或0)
     */
    root_id?: string;
    /**
     * 直接回复的父评论ID
     */
    parent_id?: string;
    /**
     * 回复对象信息 (用于前端显示 "回复 @某某")
     */
    reply_to_user_id?: string;
    reply_to_user_name?: string;
    /**
     * 互动数据
     *
     * 点赞数
     */
    like_count?: number;
    /**
     * 子评论总数 (Critical: 用于前端显示 "查看5条回复")
     */
    reply_count?: number;
    /**
     * 当前用户是否已赞
     */
    is_liked?: boolean;
    /**
     * 是否是楼主(帖子的作者)发的评论
     */
    is_author?: boolean;
    created_at?: string;
    /**
     * 预览回复 (Optimization: 仅在一级评论中返回前2-3条高热回复，避免全量拉取)
     */
    preview_replies?: Array<Comment>;
};

export type CreateCommentResponse = {
    comment?: Comment;
};

export type CreatePostRequest = {
    title?: string;
    content?: string;
    media?: Array<Media>;
    /**
     * 可以增加 tags 等
     */
    partition_id?: number;
};

export type CreatePostResponse = {
    post?: Post;
};

export type DeleteActivityResponse = {
    [key: string]: unknown;
};

/**
 * 空响应通常足够，或者返回 boolean
 */
export type DeleteCommentResponse = {
    [key: string]: unknown;
};

export type DeleteDepartmentResponse = {
    [key: string]: unknown;
};

export type DeleteHistoryEventResponse = {
    [key: string]: unknown;
};

export type DeleteMinisterResponse = {
    [key: string]: unknown;
};

export type DeletePostResponse = {
    [key: string]: unknown;
};

export type DeleteSponsorResponse = {
    [key: string]: unknown;
};

export type DeleteStaffGroupResponse = {
    [key: string]: unknown;
};

/**
 * 部门基础元数据 (Lightweight)
 * 用于：用户徽章渲染、帖子分区标签、侧边栏导航
 * 前端应该在 App 启动时拉取一次“全量 DepartmentBase 列表”并缓存
 */
export type DepartmentBase = {
    /**
     * ID
     */
    id?: string;
    /**
     * 全称 (如 "轻音部")
     */
    name?: string;
};

/**
 * 部门信息
 */
export type DepartmentInfo = {
    department_base?: DepartmentBase;
    logo?: string;
    cover_image?: string;
    /**
     * 需求提到的部门视频
     */
    intro_video_url?: string;
    description?: string;
    /**
     * 使用 repeated 保证顺序
     */
    links?: Array<Link>;
    /**
     * 排序权重，越大越靠前
     */
    sort_order?: number;
};

export type DeviceInfo = {
    /**
     * 唯一设备 ID (如 UUID 或 厂商自生成 ID)
     */
    device_id?: string;
    /**
     * 设备名 (e.g. "iPhone 14 Pro")
     */
    device_name?: string;
    platform?: DevicePlatform;
    /**
     * 系统版本 (e.g. "iOS 16.0")
     */
    os_version?: string;
    /**
     * App/前端版本号
     */
    client_version?: string;
    /**
     * 推送 Token (FCM/APNS/MiPush)
     */
    push_token?: string;
};

export type DevicePlatform = 'DEVICE_PLATFORM_UNSPECIFIED' | 'DEVICE_PLATFORM_IOS' | 'DEVICE_PLATFORM_ANDROID' | 'DEVICE_PLATFORM_WEB';

export type GetMeResponse = {
    profile?: UserProfile;
    settings?: UserSettings;
};

export type GetPostResponse = {
    post?: Post;
};

export type GetSiteConfigResponse = {
    site_name?: string;
    /**
     * 首页背景宣传视频
     */
    promo_video_url?: string;
};

export type GetUnreadCountResponse = {
    total?: number;
    /**
     * 各分类未读数，方便前端渲染 Tab 上的红点
     */
    category_interaction?: number;
    category_comment?: number;
    category_follow?: number;
    category_system?: number;
};

export type GetUploadTokensRequest = {
    scene?: ResourceScene;
    /**
     * 批量请求
     */
    tasks?: Array<UploadTask>;
};

export type GetUploadTokensResponse = {
    tokens?: Array<UploadToken>;
};

export type GetUsersResponse = {
    users?: Array<UserProfile>;
};

/**
 * 历史事件
 */
export type HistoryEvent = {
    id?: string;
    /**
     * 单独拆分年份，方便前端做时间轴分组
     */
    year?: number;
    /**
     * 显示用日期字符串 "2023.10.01"
     */
    date_str?: string;
    title?: string;
    description?: string;
    /**
     * 可能有多张图
     */
    images?: Array<string>;
};

/**
 * 首页热门动态 (聚合自社区)
 */
export type HomeTrendingItem = {
    /**
     * 原始帖子ID
     */
    id?: string;
    title?: string;
    /**
     * 封面
     */
    cover_image?: string;
    /**
     * 摘要
     */
    summary?: string;
    author_name?: string;
    author_avatar?: string;
    /**
     * 点击跳转地址 (App内链或H5链接)
     */
    jump_url?: string;
    source?: HomeTrendingItemSource;
    /**
     * 统计
     */
    like_count?: number;
};

/**
 * 外部链接结构
 */
export type Link = {
    /**
     * 链接显示文字
     */
    label?: string;
    /**
     * 实际跳转地址
     */
    url?: string;
};

export type ListActivitiesResponse = {
    list?: Array<Activity>;
};

export type ListCommentsResponse = {
    comments?: Array<Comment>;
    next_page_token?: string;
    /**
     * 该维度下的总评论数 (一级总数 或 某条评论的子回复总数)
     */
    total_count?: number;
};

export type ListDepartmentsResponse = {
    list?: Array<DepartmentInfo>;
};

export type ListHistoryResponse = {
    list?: Array<HistoryEvent>;
};

export type ListHomeTrendingResponse = {
    list?: Array<HomeTrendingItem>;
};

export type ListMinistersResponse = {
    /**
     * 按年份分组返回，方便前端渲染侧边栏年份选择
     */
    list?: Array<ListMinistersResponseYearGroup>;
};

export type ListNotificationsResponse = {
    notifications?: Array<Notification>;
    next_page_token?: string;
};

export type ListPostsResponse = {
    posts?: Array<PostPreview>;
    /**
     * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
     */
    cursor_score?: string;
    /**
     * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
     */
    cursor_timestamp?: string;
};

export type ListRelationshipsResponse = {
    /**
     * 这里不直接返回 UserSummary，建议返回 UserProfile 或者包含 RelationStatus 的对象
     * 这样在列表中就能知道"我是否也关注了这个粉丝"
     */
    users?: Array<UserProfile>;
    next_page_token?: string;
};

export type ListReportsResponse = {
    reports?: Array<Report>;
    next_page_token?: string;
};

export type ListSponsorsResponse = {
    list?: Array<Sponsor>;
};

export type ListStaffResponse = {
    list?: Array<StaffGroup>;
};

/**
 * 获取认证申请列表响应
 */
export type ListVerificationApplicationsResponse = {
    applications?: Array<VerificationApplication>;
    next_page_token?: string;
};

export type LoginRequest = {
    /**
     * 凭证载荷：QQ 传 AccessToken
     */
    credential?: string;
    device?: DeviceInfo;
};

export type LoginResponse = {
    /**
     * 短期令牌 (如 2小时)，过期绝对时间戳及user_id放在payload中
     */
    access_token?: string;
    /**
     * 长期令牌 (如 30天)，过期绝对时间戳放在payload中
     */
    refresh_token?: string;
    user?: UserSummary;
};

export type LogoutResponse = {
    [key: string]: unknown;
};

export type MarkReadRequest = {
    scope?: MarkReadRequestScope;
    category?: NotificationCategory;
    /**
     * 当 scope=ID 时必填 (支持批量)
     */
    notification_ids?: Array<string>;
};

export type MarkReadResponse = {
    [key: string]: unknown;
};

/**
 * 多媒体资源
 */
export type Media = {
    /**
     * "image" | "video"
     */
    type?: string;
    /**
     * 资源地址
     */
    url?: string;
    /**
     * 缩略图（视频用）
     */
    thumbnail?: string;
    /**
     * 宽
     */
    width?: number;
    /**
     * 高
     */
    height?: number;
};

/**
 * 部长
 */
export type Minister = {
    id?: string;
    /**
     * CN (需求中的 name)
     */
    name?: string;
    avatar?: string;
    /**
     * 签名
     */
    signature?: string;
    /**
     * 简介
     */
    description?: string;
    /**
     * 所属部门名称
     */
    department_name?: string;
    /**
     * 届数/年份信息
     *
     * 第几届 (需求提到的按年代/代目划分)
     */
    session_number?: number;
    /**
     * 任职年份
     */
    year?: number;
    links?: Array<Link>;
};

export type ModifyDepartmentsRequest = {
    /**
     * 选择的部门 ID 列表
     */
    ids?: Array<string>;
};

export type ModifyDepartmentsResponse = {
    [key: string]: unknown;
};

export type Notification = {
    notification_id?: string;
    type?: NotificationType;
    category?: NotificationCategory;
    /**
     * --- 触发者信息 ---
     * 聚合展示逻辑：如果是 TYPE_LIKE_POST，这里可能是 1 人，也可能是 "A, B 等 5 人"
     * 后端在列表返回时，只返回最近的 1-3 个头像即可
     */
    actors?: Array<UserSummary>;
    /**
     * 总参与人数 (如果大于 actors.length，前端显示 "等N人")
     */
    actor_count?: number;
    /**
     * --- 核心内容 ---
     *
     * 标题 (系统通知用，或者显示 "评论了你")
     */
    title?: string;
    /**
     * 内容 (评论的文本内容，或者系统通知详情)
     */
    content?: string;
    /**
     * --- 目标/上下文快照 (Snapshot) ---
     * 关键优化：让前端在列表页能直接渲染出“被赞的是哪张图”
     *
     * 帖子ID 或 评论ID
     */
    target_id?: string;
    /**
     * post / comment / url
     */
    target_type?: string;
    /**
     * 被赞帖子/被评论帖子的封面图
     */
    target_preview_image?: string;
    /**
     * 被赞评论的原文摘要 (截取前20字)
     */
    target_summary?: string;
    /**
     * --- 跳转逻辑 ---
     * 用于系统通知点击后跳转到 WebView 或 App 内特定页面
     */
    redirect_url?: string;
    is_read?: boolean;
    created_at?: string;
};

/**
 * 通知大类 (用于列表筛选和角标统计)
 *
 * - CATEGORY_INTERACTION: 赞、收藏 (通常合并展示)
 * - CATEGORY_COMMENT: 评论、@提到 (通常合并展示)
 * - CATEGORY_FOLLOW: 新增关注
 * - CATEGORY_SYSTEM: 系统通知 (活动、公告、举报反馈)
 */
export type NotificationCategory = 'CATEGORY_UNSPECIFIED' | 'CATEGORY_INTERACTION' | 'CATEGORY_COMMENT' | 'CATEGORY_FOLLOW' | 'CATEGORY_SYSTEM';

/**
 * 通知设置 (仅自己可见)
 */
export type NotificationSettings = {
    /**
     * 全局推送开关
     */
    push_enabled?: boolean;
    /**
     * 私信推送
     */
    push_chat?: boolean;
    /**
     * 评论与 @ 推送
     */
    push_comment_at?: boolean;
    /**
     * 点赞与收藏推送
     */
    push_like_collect?: boolean;
    /**
     * 新粉丝推送
     */
    push_new_follower?: boolean;
    /**
     * 关注动态推送
     */
    push_post_update?: boolean;
    /**
     * 系统/举报反馈推送
     */
    push_system?: boolean;
};

/**
 * 通知具体类型 (用于前端渲染不同的 UI 模板)
 *
 * - TYPE_LIKE_POST: 互动类
 *
 * 赞了帖子
 * - TYPE_LIKE_COMMENT: 赞了评论
 * - TYPE_COLLECT_POST: 收藏了帖子
 * - TYPE_COMMENT_POST: 内容类
 *
 * 评论了帖子
 * - TYPE_REPLY_COMMENT: 回复了评论
 * - TYPE_MENTION: @了你
 * - TYPE_FOLLOW: 关系类
 *
 * 关注了你
 * - TYPE_SYSTEM_ANNOUNCEMENT: 系统类
 *
 * 官方公告 (晒你宣传视频等)
 * - TYPE_REPORT_RESULT: 举报处理结果
 */
export type NotificationType = 'TYPE_UNSPECIFIED' | 'TYPE_LIKE_POST' | 'TYPE_LIKE_COMMENT' | 'TYPE_COLLECT_POST' | 'TYPE_COMMENT_POST' | 'TYPE_REPLY_COMMENT' | 'TYPE_MENTION' | 'TYPE_FOLLOW' | 'TYPE_SYSTEM_ANNOUNCEMENT' | 'TYPE_REPORT_RESULT';

/**
 * - ORDER_TYPE_RECOMMENDED: 推荐排序
 * - ORDER_TYPE_LATEST: 最新排序
 * - ORDER_TYPE_HOT: 热门排序
 */
export type OrderType = 'ORDER_TYPE_UNSPECIFIED' | 'ORDER_TYPE_RECOMMENDED' | 'ORDER_TYPE_LATEST' | 'ORDER_TYPE_HOT';

/**
 * 分页请求
 */
export type Pagination = {
    /**
     * 游标（用于无限滚动，最后一条数据的id）
     */
    page_token?: string;
    need_num?: number;
};

export type Post = {
    post_id?: string;
    author?: UserSummary;
    title?: string;
    /**
     * 详情页返回全文
     */
    content?: string;
    /**
     * 后面需更改media结构
     */
    media?: Array<Media>;
    /**
     * 交互数据
     */
    like_count?: number;
    comment_count?: number;
    collect_count?: number;
    view_count?: number;
    /**
     * 当前用户状态
     */
    is_liked?: boolean;
    is_collected?: boolean;
    /**
     * 新增：是否已关注作者
     */
    is_following_author?: boolean;
    /**
     * 新增：作者是否已关注当前用户
     */
    is_followed_by_author?: boolean;
    /**
     * 时间与状态
     */
    publish_time?: string;
    edit_time?: string;
    status?: PostStatus;
};

/**
 * 具体的筛选器
 */
export type PostFilter = {
    /**
     * 关键词搜索
     */
    keyword?: string;
    time_range?: TimeRange;
};

/**
 * 帖子预览（卡片视图数据）
 */
export type PostPreview = {
    /**
     * 基础信息
     */
    post_id?: string;
    title?: string;
    /**
     * 摘要：后端截取内容的前N个字符（如前60字），去除Markdown/HTML格式，用于纯文本展示
     */
    summary?: string;
    cover?: Media;
    author?: UserSummary;
    /**
     * 核心统计数据
     */
    like_count?: number;
    /**
     * 列表页通常也显示浏览量
     */
    view_count?: number;
    /**
     * 显眼的评论数能引导点击
     */
    comment_count?: number;
    /**
     * 状态标记 (前端用于渲染 UI 状态)
     *
     * 当前用户是否点赞
     */
    is_liked?: boolean;
    /**
     * UI上是否显示一个“播放”的小图标
     */
    is_only_video?: boolean;
    /**
     * 辅助信息
     *
     * 发布时间戳，前端显示 "3小时前"
     */
    publish_time?: string;
};

/**
 * - POST_STATUS_PUBLISHED: 已发布
 * - POST_STATUS_AUDITING: 审核中
 * - POST_STATUS_DELETED: 已删除
 */
export type PostStatus = 'POST_STATUS_UNSPECIFIED' | 'POST_STATUS_PUBLISHED' | 'POST_STATUS_AUDITING' | 'POST_STATUS_DELETED';

/**
 * 隐私设置 (仅自己可见)
 */
export type PrivacySettings = {
    message_permission?: ChatPrivacyLevel;
    liked_posts_visibility?: BasePrivacyLevel;
    collected_posts_visibility?: BasePrivacyLevel;
};

export type RefreshTokenRequest = {
    refresh_token?: string;
};

export type RefreshTokenResponse = {
    access_token?: string;
    /**
     * 可选：实现 RefreshToken 轮转机制时，会下发新的 RT
     */
    refresh_token?: string;
};

/**
 * ---------------------------------------------------------
 * 统一筛选请求设计 (The Unified Request)
 * ---------------------------------------------------------
 *
 * - REFRESH_TYPE_PULL_DOWN: 下拉刷新，获取最新数据
 * - REFRESH_TYPE_PULL_UP: 上拉加载，获取历史数据
 */
export type RefreshType = 'REFRESH_TYPE_UNSPECIFIED' | 'REFRESH_TYPE_PULL_DOWN' | 'REFRESH_TYPE_PULL_UP';

export type Report = {
    id?: string;
    reporter_id?: string;
    target_id?: string;
    type?: ReportTargetType;
    reason?: string;
    status?: ReportStatus;
    created_at?: string;
};

/**
 * - REPORT_STATUS_REJECTED: 驳回
 */
export type ReportStatus = 'REPORT_STATUS_PENDING' | 'REPORT_STATUS_RESOLVED' | 'REPORT_STATUS_REJECTED';

export type ReportTargetType = 'REPORT_TARGET_TYPE_POST' | 'REPORT_TARGET_TYPE_COMMENT' | 'REPORT_TARGET_TYPE_USER';

export type ResolveReportResponse = {
    [key: string]: unknown;
};

/**
 * - SCENE_USER_AVATAR: 用户头像 (限制如 <2MB, 正方形)
 * - SCENE_POST_IMAGE: 帖子图片 (限制如 <10MB)
 * - SCENE_POST_VIDEO: 帖子视频 (限制如 <500MB)
 * - SCENE_COMMENT_IMAGE: 评论图片
 * - SCENE_CHAT_FILE: 私聊文件 (可能需要私有读权限)
 */
export type ResourceScene = 'SCENE_UNSPECIFIED' | 'SCENE_USER_AVATAR' | 'SCENE_POST_IMAGE' | 'SCENE_POST_VIDEO' | 'SCENE_COMMENT_IMAGE' | 'SCENE_CHAT_FILE';

/**
 * 用户角色枚举
 *
 * - ROLE_VISITOR: 游客
 * - ROLE_USER: 用户
 * - ROLE_ADMIN: 内容管理员
 * - ROLE_SUPER_ADMIN: 超级管理员
 */
export type Role = 'ROLE_VISITOR' | 'ROLE_USER' | 'ROLE_ADMIN' | 'ROLE_SUPER_ADMIN';

export type SetCollectResponse = {
    is_active?: boolean;
    /**
     * 操作后的最新收藏数
     */
    collect_count?: number;
};

export type SetFollowResponse = {
    is_active?: boolean;
    /**
     * 返回是否变成了互关，前端可显示"互相关注"图标
     */
    is_mutual?: boolean;
};

export type SetLikeResponse = {
    /**
     * 最终状态
     */
    is_active?: boolean;
    /**
     * 操作后的最新点赞数 (UI直接更新这个数字)
     */
    like_count?: number;
};

/**
 * 赞助者 (如果和Staff页面分开展示)
 */
export type Sponsor = {
    name?: string;
    avatar?: string;
    intro?: string;
    /**
     * 显示金额，如 "￥50.00"
     */
    amount_display?: string;
};

/**
 * Staff 分组 (如：开发组、设计组、甚至 赞助组 也可以复用这个结构)
 */
export type StaffGroup = {
    group_name?: string;
    members?: Array<StaffMember>;
};

/**
 * Staff 成员
 */
export type StaffMember = {
    /**
     * CN
     */
    name?: string;
    avatar?: string;
    /**
     * 职责 (e.g. "后端开发")
     */
    role?: string;
    /**
     * 简介/寄语
     */
    description?: string;
    /**
     * (可选) 赞助金额，对应需求
     */
    donation_amount?: string;
    links?: Array<Link>;
};

export type TargetType = 'TARGET_TYPE_UNSPECIFIED' | 'TARGET_TYPE_POST' | 'TARGET_TYPE_COMMENT';

export type TimeRange = {
    /**
     * 开始时间
     */
    start_timestamp?: string;
    /**
     * 结束时间
     */
    end_timestamp?: string;
};

export type UpdateProfileResponse = {
    [key: string]: unknown;
};

export type UpdatePushTokenRequest = {
    push_token?: string;
    /**
     * 标识是哪个设备变更了 token
     */
    device_id?: string;
};

export type UpdatePushTokenResponse = {
    [key: string]: unknown;
};

export type UpdateSettingsResponse = {
    [key: string]: unknown;
};

export type UpdateUserRoleRequest = {
    user_ids?: Array<string>;
    role?: Role;
};

export type UpdateUserRoleResponse = {
    [key: string]: unknown;
};

export type UploadTask = {
    /**
     * 原始文件名 (e.g. "photo.jpg")
     */
    filename?: string;
    /**
     * 文件大小 (字节)
     */
    size_bytes?: string;
    /**
     * MIME类型 (e.g. "image/jpeg", "video/mp4")
     */
    mime_type?: string;
    /**
     * (可选) MD5/SHA256，用于秒传检测
     */
    file_hash?: string;
};

export type UploadToken = {
    /**
     * 对应请求中的文件名或索引
     */
    task_id?: string;
    /**
     * 上传地址 (PUT Signed URL)
     */
    upload_url?: string;
    /**
     * 最终访问地址 (存入 DB 的地址)
     */
    public_url?: string;
    /**
     * HTTP Header 要求 (通常 PUT 上传需要指定 Content-Type)
     */
    required_headers?: {
        [key: string]: string;
    };
    /**
     * 秒传标志
     *
     * 如果为 true，说明 hash 已存在，无需上传，直接使用 public_url
     */
    skip_upload?: boolean;
};

/**
 * 活动管理
 */
export type UpsertActivityRequest = {
    activity?: Activity;
};

export type UpsertActivityResponse = {
    activity_id?: string;
};

/**
 * 部门管理
 */
export type UpsertDepartmentRequest = {
    department?: DepartmentInfo;
};

export type UpsertDepartmentResponse = {
    department_id?: string;
};

/**
 * 历史事件管理
 */
export type UpsertHistoryEventRequest = {
    history_event?: HistoryEvent;
};

export type UpsertHistoryEventResponse = {
    event_id?: string;
};

/**
 * 部长管理
 */
export type UpsertMinisterRequest = {
    minister?: Minister;
};

export type UpsertMinisterResponse = {
    minister_id?: string;
};

/**
 * 赞助者管理
 */
export type UpsertSponsorRequest = {
    sponsor?: Sponsor;
};

export type UpsertSponsorResponse = {
    sponsor_id?: string;
};

/**
 * Staff 管理
 */
export type UpsertStaffGroupRequest = {
    staff_group?: StaffGroup;
};

export type UpsertStaffGroupResponse = {
    group_id?: string;
};

/**
 * 用户公开资料 (他人可见)
 */
export type UserProfile = {
    base?: UserSummary;
    /**
     * 外部链接
     */
    links?: Array<Link>;
    stats?: UserStats;
    relation_status?: UserRelationStatus;
    role?: Role;
};

/**
 * 关系状态 (计算后的结果)
 */
export type UserRelationStatus = {
    /**
     * 我是否关注了他
     */
    is_following?: boolean;
    /**
     * 他是否关注了我 (互关判断)
     */
    is_followed_by?: boolean;
    /**
     * bool is_blocking = 3;        // 我是否拉黑了他
     *
     * 用户原名
     */
    origin_name?: string;
    /**
     * 隐私权限结果 (Critical: 不要返回 PrivacySettings，返回 Capability)
     *
     * 是否能发私信
     */
    can_send_message?: boolean;
    /**
     * bool can_view_list = 11;     // 是否能看他的关注列表
     *
     * 是否能看他的点赞帖子
     */
    can_view_liked_posts?: boolean;
    /**
     * 是否能看他的收藏帖子
     */
    can_view_collected_posts?: boolean;
};

/**
 * 用户通用设置 (仅自己可见)
 */
export type UserSettings = {
    notification?: NotificationSettings;
    privacy?: PrivacySettings;
    appearance?: AppearanceSettings;
};

/**
 * 统计数据
 */
export type UserStats = {
    follower_count?: string;
    following_count?: string;
    /**
     * 获得的赞
     */
    like_count_received?: string;
    /**
     * 获得的收藏
     */
    collect_count_received?: string;
    /**
     * 获得浏览
     */
    view_count_received?: string;
};

/**
 * 基础信息摘要（用于瀑布流、列表页）
 */
export type UserSummary = {
    user_id?: string;
    /**
     * 昵称，若有备注优先显示备注
     */
    nickname?: string;
    avatar?: string;
    /**
     * 所有所属部门徽章
     */
    departments?: Array<DepartmentBase>;
    /**
     * 身份认证状态
     */
    is_verified?: boolean;
    /**
     * 认证头衔（如：23届部长）
     */
    verified_title?: string;
};

/**
 * 认证申请信息
 */
export type VerificationApplication = {
    /**
     * 申请ID
     */
    application_id?: string;
    /**
     * 申请人ID
     */
    user_id?: string;
    user?: UserSummary;
    /**
     * 申请的认证头衔
     */
    verified_title?: string;
    status?: VerificationStatus;
    /**
     * 驳回原因 (仅当 status 为 REJECTED 时有效)
     */
    reject_reason?: string;
    /**
     * 申请时间戳
     */
    created_at?: string;
    /**
     * 处理时间戳
     */
    processed_at?: string;
    /**
     * 处理人ID
     */
    processed_by?: string;
};

/**
 * 认证申请状态枚举
 *
 * - VERIFICATION_STATUS_PENDING: 待审核
 * - VERIFICATION_STATUS_APPROVED: 已通过
 * - VERIFICATION_STATUS_REJECTED: 已驳回
 */
export type VerificationStatus = 'VERIFICATION_STATUS_PENDING' | 'VERIFICATION_STATUS_APPROVED' | 'VERIFICATION_STATUS_REJECTED';

export type PortalServiceListActivitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/activities';
};

export type PortalServiceListActivitiesErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PortalServiceListActivitiesError = PortalServiceListActivitiesErrors[keyof PortalServiceListActivitiesErrors];

export type PortalServiceListActivitiesResponses = {
    /**
     * A successful response.
     */
    200: ListActivitiesResponse;
};

export type PortalServiceListActivitiesResponse = PortalServiceListActivitiesResponses[keyof PortalServiceListActivitiesResponses];

export type SiteAdminServiceUpsertActivityData = {
    body: UpsertActivityRequest;
    path?: never;
    query?: never;
    url: '/v1/admin/activities';
};

export type SiteAdminServiceUpsertActivityErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceUpsertActivityError = SiteAdminServiceUpsertActivityErrors[keyof SiteAdminServiceUpsertActivityErrors];

export type SiteAdminServiceUpsertActivityResponses = {
    /**
     * A successful response.
     */
    200: UpsertActivityResponse;
};

export type SiteAdminServiceUpsertActivityResponse = SiteAdminServiceUpsertActivityResponses[keyof SiteAdminServiceUpsertActivityResponses];

export type SiteAdminServiceDeleteActivityData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/admin/activities/{id}';
};

export type SiteAdminServiceDeleteActivityErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceDeleteActivityError = SiteAdminServiceDeleteActivityErrors[keyof SiteAdminServiceDeleteActivityErrors];

export type SiteAdminServiceDeleteActivityResponses = {
    /**
     * A successful response.
     */
    200: DeleteActivityResponse;
};

export type SiteAdminServiceDeleteActivityResponse = SiteAdminServiceDeleteActivityResponses[keyof SiteAdminServiceDeleteActivityResponses];

export type UserAdminServiceBanData = {
    body: BanRequest;
    path?: never;
    query?: never;
    url: '/v1/admin/ban';
};

export type UserAdminServiceBanErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserAdminServiceBanError = UserAdminServiceBanErrors[keyof UserAdminServiceBanErrors];

export type UserAdminServiceBanResponses = {
    /**
     * A successful response.
     */
    200: BanResponse;
};

export type UserAdminServiceBanResponse = UserAdminServiceBanResponses[keyof UserAdminServiceBanResponses];

export type SiteAdminServiceUpsertDepartmentData = {
    body: UpsertDepartmentRequest;
    path?: never;
    query?: never;
    url: '/v1/admin/departments';
};

export type SiteAdminServiceUpsertDepartmentErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceUpsertDepartmentError = SiteAdminServiceUpsertDepartmentErrors[keyof SiteAdminServiceUpsertDepartmentErrors];

export type SiteAdminServiceUpsertDepartmentResponses = {
    /**
     * A successful response.
     */
    200: UpsertDepartmentResponse;
};

export type SiteAdminServiceUpsertDepartmentResponse = SiteAdminServiceUpsertDepartmentResponses[keyof SiteAdminServiceUpsertDepartmentResponses];

export type SiteAdminServiceDeleteDepartmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/admin/departments/{id}';
};

export type SiteAdminServiceDeleteDepartmentErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceDeleteDepartmentError = SiteAdminServiceDeleteDepartmentErrors[keyof SiteAdminServiceDeleteDepartmentErrors];

export type SiteAdminServiceDeleteDepartmentResponses = {
    /**
     * A successful response.
     */
    200: DeleteDepartmentResponse;
};

export type SiteAdminServiceDeleteDepartmentResponse = SiteAdminServiceDeleteDepartmentResponses[keyof SiteAdminServiceDeleteDepartmentResponses];

export type SiteAdminServiceUpsertHistoryEventData = {
    body: UpsertHistoryEventRequest;
    path?: never;
    query?: never;
    url: '/v1/admin/history-events';
};

export type SiteAdminServiceUpsertHistoryEventErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceUpsertHistoryEventError = SiteAdminServiceUpsertHistoryEventErrors[keyof SiteAdminServiceUpsertHistoryEventErrors];

export type SiteAdminServiceUpsertHistoryEventResponses = {
    /**
     * A successful response.
     */
    200: UpsertHistoryEventResponse;
};

export type SiteAdminServiceUpsertHistoryEventResponse = SiteAdminServiceUpsertHistoryEventResponses[keyof SiteAdminServiceUpsertHistoryEventResponses];

export type SiteAdminServiceDeleteHistoryEventData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/admin/history-events/{id}';
};

export type SiteAdminServiceDeleteHistoryEventErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceDeleteHistoryEventError = SiteAdminServiceDeleteHistoryEventErrors[keyof SiteAdminServiceDeleteHistoryEventErrors];

export type SiteAdminServiceDeleteHistoryEventResponses = {
    /**
     * A successful response.
     */
    200: DeleteHistoryEventResponse;
};

export type SiteAdminServiceDeleteHistoryEventResponse = SiteAdminServiceDeleteHistoryEventResponses[keyof SiteAdminServiceDeleteHistoryEventResponses];

export type SiteAdminServiceUpsertMinisterData = {
    body: UpsertMinisterRequest;
    path?: never;
    query?: never;
    url: '/v1/admin/ministers';
};

export type SiteAdminServiceUpsertMinisterErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceUpsertMinisterError = SiteAdminServiceUpsertMinisterErrors[keyof SiteAdminServiceUpsertMinisterErrors];

export type SiteAdminServiceUpsertMinisterResponses = {
    /**
     * A successful response.
     */
    200: UpsertMinisterResponse;
};

export type SiteAdminServiceUpsertMinisterResponse = SiteAdminServiceUpsertMinisterResponses[keyof SiteAdminServiceUpsertMinisterResponses];

export type SiteAdminServiceDeleteMinisterData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/admin/ministers/{id}';
};

export type SiteAdminServiceDeleteMinisterErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceDeleteMinisterError = SiteAdminServiceDeleteMinisterErrors[keyof SiteAdminServiceDeleteMinisterErrors];

export type SiteAdminServiceDeleteMinisterResponses = {
    /**
     * A successful response.
     */
    200: DeleteMinisterResponse;
};

export type SiteAdminServiceDeleteMinisterResponse = SiteAdminServiceDeleteMinisterResponses[keyof SiteAdminServiceDeleteMinisterResponses];

export type GovernanceServiceListReportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         *  - REPORT_STATUS_REJECTED: 驳回
         */
        status?: 'REPORT_STATUS_PENDING' | 'REPORT_STATUS_RESOLVED' | 'REPORT_STATUS_REJECTED';
        /**
         * 游标（用于无限滚动，最后一条数据的id）
         */
        'pagination.page_token'?: string;
        'pagination.need_num'?: number;
    };
    url: '/v1/admin/reports';
};

export type GovernanceServiceListReportsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type GovernanceServiceListReportsError = GovernanceServiceListReportsErrors[keyof GovernanceServiceListReportsErrors];

export type GovernanceServiceListReportsResponses = {
    /**
     * A successful response.
     */
    200: ListReportsResponse;
};

export type GovernanceServiceListReportsResponse = GovernanceServiceListReportsResponses[keyof GovernanceServiceListReportsResponses];

export type GovernanceServiceResolveReportData = {
    body: GovernanceServiceResolveReportBody;
    path: {
        report_id: string;
    };
    query?: never;
    url: '/v1/admin/reports/{report_id}';
};

export type GovernanceServiceResolveReportErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type GovernanceServiceResolveReportError = GovernanceServiceResolveReportErrors[keyof GovernanceServiceResolveReportErrors];

export type GovernanceServiceResolveReportResponses = {
    /**
     * A successful response.
     */
    200: ResolveReportResponse;
};

export type GovernanceServiceResolveReportResponse = GovernanceServiceResolveReportResponses[keyof GovernanceServiceResolveReportResponses];

export type SiteAdminServiceUpsertSponsorData = {
    body: UpsertSponsorRequest;
    path?: never;
    query?: never;
    url: '/v1/admin/sponsors';
};

export type SiteAdminServiceUpsertSponsorErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceUpsertSponsorError = SiteAdminServiceUpsertSponsorErrors[keyof SiteAdminServiceUpsertSponsorErrors];

export type SiteAdminServiceUpsertSponsorResponses = {
    /**
     * A successful response.
     */
    200: UpsertSponsorResponse;
};

export type SiteAdminServiceUpsertSponsorResponse = SiteAdminServiceUpsertSponsorResponses[keyof SiteAdminServiceUpsertSponsorResponses];

export type SiteAdminServiceDeleteSponsorData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/admin/sponsors/{id}';
};

export type SiteAdminServiceDeleteSponsorErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceDeleteSponsorError = SiteAdminServiceDeleteSponsorErrors[keyof SiteAdminServiceDeleteSponsorErrors];

export type SiteAdminServiceDeleteSponsorResponses = {
    /**
     * A successful response.
     */
    200: DeleteSponsorResponse;
};

export type SiteAdminServiceDeleteSponsorResponse = SiteAdminServiceDeleteSponsorResponses[keyof SiteAdminServiceDeleteSponsorResponses];

export type SiteAdminServiceUpsertStaffGroupData = {
    body: UpsertStaffGroupRequest;
    path?: never;
    query?: never;
    url: '/v1/admin/staff-groups';
};

export type SiteAdminServiceUpsertStaffGroupErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceUpsertStaffGroupError = SiteAdminServiceUpsertStaffGroupErrors[keyof SiteAdminServiceUpsertStaffGroupErrors];

export type SiteAdminServiceUpsertStaffGroupResponses = {
    /**
     * A successful response.
     */
    200: UpsertStaffGroupResponse;
};

export type SiteAdminServiceUpsertStaffGroupResponse = SiteAdminServiceUpsertStaffGroupResponses[keyof SiteAdminServiceUpsertStaffGroupResponses];

export type SiteAdminServiceDeleteStaffGroupData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/admin/staff-groups/{id}';
};

export type SiteAdminServiceDeleteStaffGroupErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SiteAdminServiceDeleteStaffGroupError = SiteAdminServiceDeleteStaffGroupErrors[keyof SiteAdminServiceDeleteStaffGroupErrors];

export type SiteAdminServiceDeleteStaffGroupResponses = {
    /**
     * A successful response.
     */
    200: DeleteStaffGroupResponse;
};

export type SiteAdminServiceDeleteStaffGroupResponse = SiteAdminServiceDeleteStaffGroupResponses[keyof SiteAdminServiceDeleteStaffGroupResponses];

export type UserAdminServiceUpdateUsersRoleData = {
    body: UpdateUserRoleRequest;
    path?: never;
    query?: never;
    url: '/v1/admin/users/role';
};

export type UserAdminServiceUpdateUsersRoleErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserAdminServiceUpdateUsersRoleError = UserAdminServiceUpdateUsersRoleErrors[keyof UserAdminServiceUpdateUsersRoleErrors];

export type UserAdminServiceUpdateUsersRoleResponses = {
    /**
     * A successful response.
     */
    200: UpdateUserRoleResponse;
};

export type UserAdminServiceUpdateUsersRoleResponse = UserAdminServiceUpdateUsersRoleResponses[keyof UserAdminServiceUpdateUsersRoleResponses];

export type UserAdminServiceListVerificationApplicationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 筛选状态 (可选，默认 PENDING)
         *
         * - VERIFICATION_STATUS_PENDING: 待审核
         * - VERIFICATION_STATUS_APPROVED: 已通过
         * - VERIFICATION_STATUS_REJECTED: 已驳回
         */
        status?: 'VERIFICATION_STATUS_PENDING' | 'VERIFICATION_STATUS_APPROVED' | 'VERIFICATION_STATUS_REJECTED';
        /**
         * 游标（用于无限滚动，最后一条数据的id）
         */
        'pagination.page_token'?: string;
        'pagination.need_num'?: number;
    };
    url: '/v1/admin/verifications';
};

export type UserAdminServiceListVerificationApplicationsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserAdminServiceListVerificationApplicationsError = UserAdminServiceListVerificationApplicationsErrors[keyof UserAdminServiceListVerificationApplicationsErrors];

export type UserAdminServiceListVerificationApplicationsResponses = {
    /**
     * A successful response.
     */
    200: ListVerificationApplicationsResponse;
};

export type UserAdminServiceListVerificationApplicationsResponse = UserAdminServiceListVerificationApplicationsResponses[keyof UserAdminServiceListVerificationApplicationsResponses];

export type UserAdminServiceApproveVerificationData = {
    body: UserAdminServiceApproveVerificationBody;
    path: {
        /**
         * 申请ID
         */
        application_id: string;
    };
    query?: never;
    url: '/v1/admin/verifications/{application_id}';
};

export type UserAdminServiceApproveVerificationErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserAdminServiceApproveVerificationError = UserAdminServiceApproveVerificationErrors[keyof UserAdminServiceApproveVerificationErrors];

export type UserAdminServiceApproveVerificationResponses = {
    /**
     * A successful response.
     */
    200: ApproveVerificationResponse;
};

export type UserAdminServiceApproveVerificationResponse = UserAdminServiceApproveVerificationResponses[keyof UserAdminServiceApproveVerificationResponses];

export type AuthServiceLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type AuthServiceLoginErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type AuthServiceLoginError = AuthServiceLoginErrors[keyof AuthServiceLoginErrors];

export type AuthServiceLoginResponses = {
    /**
     * A successful response.
     */
    200: LoginResponse;
};

export type AuthServiceLoginResponse = AuthServiceLoginResponses[keyof AuthServiceLoginResponses];

export type AuthServiceLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/logout';
};

export type AuthServiceLogoutErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type AuthServiceLogoutError = AuthServiceLogoutErrors[keyof AuthServiceLogoutErrors];

export type AuthServiceLogoutResponses = {
    /**
     * A successful response.
     */
    200: LogoutResponse;
};

export type AuthServiceLogoutResponse = AuthServiceLogoutResponses[keyof AuthServiceLogoutResponses];

export type AuthServiceUpdatePushTokenData = {
    body: UpdatePushTokenRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/push-token';
};

export type AuthServiceUpdatePushTokenErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type AuthServiceUpdatePushTokenError = AuthServiceUpdatePushTokenErrors[keyof AuthServiceUpdatePushTokenErrors];

export type AuthServiceUpdatePushTokenResponses = {
    /**
     * A successful response.
     */
    200: UpdatePushTokenResponse;
};

export type AuthServiceUpdatePushTokenResponse = AuthServiceUpdatePushTokenResponses[keyof AuthServiceUpdatePushTokenResponses];

export type AuthServiceRefreshTokenData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/refresh';
};

export type AuthServiceRefreshTokenErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type AuthServiceRefreshTokenError = AuthServiceRefreshTokenErrors[keyof AuthServiceRefreshTokenErrors];

export type AuthServiceRefreshTokenResponses = {
    /**
     * A successful response.
     */
    200: RefreshTokenResponse;
};

export type AuthServiceRefreshTokenResponse = AuthServiceRefreshTokenResponses[keyof AuthServiceRefreshTokenResponses];

export type InteractionServiceSetCollectData = {
    body: InteractionServiceSetCollectBody;
    path: {
        post_id: string;
    };
    query?: never;
    url: '/v1/collections/{post_id}';
};

export type InteractionServiceSetCollectErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type InteractionServiceSetCollectError = InteractionServiceSetCollectErrors[keyof InteractionServiceSetCollectErrors];

export type InteractionServiceSetCollectResponses = {
    /**
     * A successful response.
     */
    200: SetCollectResponse;
};

export type InteractionServiceSetCollectResponse = InteractionServiceSetCollectResponses[keyof InteractionServiceSetCollectResponses];

export type CommentServiceDeleteCommentData = {
    body?: never;
    path: {
        comment_id: string;
    };
    query?: never;
    url: '/v1/comments/{comment_id}';
};

export type CommentServiceDeleteCommentErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type CommentServiceDeleteCommentError = CommentServiceDeleteCommentErrors[keyof CommentServiceDeleteCommentErrors];

export type CommentServiceDeleteCommentResponses = {
    /**
     * A successful response.
     */
    200: DeleteCommentResponse;
};

export type CommentServiceDeleteCommentResponse = CommentServiceDeleteCommentResponses[keyof CommentServiceDeleteCommentResponses];

export type PortalServiceListDepartmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/departments';
};

export type PortalServiceListDepartmentsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PortalServiceListDepartmentsError = PortalServiceListDepartmentsErrors[keyof PortalServiceListDepartmentsErrors];

export type PortalServiceListDepartmentsResponses = {
    /**
     * A successful response.
     */
    200: ListDepartmentsResponse;
};

export type PortalServiceListDepartmentsResponse = PortalServiceListDepartmentsResponses[keyof PortalServiceListDepartmentsResponses];

export type PortalServiceListHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/history';
};

export type PortalServiceListHistoryErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PortalServiceListHistoryError = PortalServiceListHistoryErrors[keyof PortalServiceListHistoryErrors];

export type PortalServiceListHistoryResponses = {
    /**
     * A successful response.
     */
    200: ListHistoryResponse;
};

export type PortalServiceListHistoryResponse = PortalServiceListHistoryResponses[keyof PortalServiceListHistoryResponses];

export type InteractionServiceSetLikeData = {
    body: InteractionServiceSetLikeBody;
    path: {
        /**
         * PostID 或 CommentID
         */
        target_id: string;
    };
    query?: never;
    url: '/v1/likes/{target_id}';
};

export type InteractionServiceSetLikeErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type InteractionServiceSetLikeError = InteractionServiceSetLikeErrors[keyof InteractionServiceSetLikeErrors];

export type InteractionServiceSetLikeResponses = {
    /**
     * A successful response.
     */
    200: SetLikeResponse;
};

export type InteractionServiceSetLikeResponse = InteractionServiceSetLikeResponses[keyof InteractionServiceSetLikeResponses];

export type UserServiceGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/me';
};

export type UserServiceGetMeErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceGetMeError = UserServiceGetMeErrors[keyof UserServiceGetMeErrors];

export type UserServiceGetMeResponses = {
    /**
     * A successful response.
     */
    200: GetMeResponse;
};

export type UserServiceGetMeResponse = UserServiceGetMeResponses[keyof UserServiceGetMeResponses];

export type UserServiceModifyDepartmentsData = {
    body: ModifyDepartmentsRequest;
    path?: never;
    query?: never;
    url: '/v1/me/departments';
};

export type UserServiceModifyDepartmentsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceModifyDepartmentsError = UserServiceModifyDepartmentsErrors[keyof UserServiceModifyDepartmentsErrors];

export type UserServiceModifyDepartmentsResponses = {
    /**
     * A successful response.
     */
    200: ModifyDepartmentsResponse;
};

export type UserServiceModifyDepartmentsResponse = UserServiceModifyDepartmentsResponses[keyof UserServiceModifyDepartmentsResponses];

export type UserServiceSetFollowData = {
    body: UserServiceSetFollowBody;
    path: {
        target_user_id: string;
    };
    query?: never;
    url: '/v1/me/following/{target_user_id}';
};

export type UserServiceSetFollowErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceSetFollowError = UserServiceSetFollowErrors[keyof UserServiceSetFollowErrors];

export type UserServiceSetFollowResponses = {
    /**
     * A successful response.
     */
    200: SetFollowResponse;
};

export type UserServiceSetFollowResponse = UserServiceSetFollowResponses[keyof UserServiceSetFollowResponses];

export type UserServiceUpdateProfileData = {
    body: UserProfile;
    path?: never;
    query?: never;
    url: '/v1/me/profile';
};

export type UserServiceUpdateProfileErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceUpdateProfileError = UserServiceUpdateProfileErrors[keyof UserServiceUpdateProfileErrors];

export type UserServiceUpdateProfileResponses = {
    /**
     * A successful response.
     */
    200: UpdateProfileResponse;
};

export type UserServiceUpdateProfileResponse = UserServiceUpdateProfileResponses[keyof UserServiceUpdateProfileResponses];

export type UserServiceUpdateSettingsData = {
    /**
     * 可选：将 Privacy 和 UserSettings 分开传，或者合并
     */
    body: UserSettings;
    path?: never;
    query?: never;
    url: '/v1/me/settings';
};

export type UserServiceUpdateSettingsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceUpdateSettingsError = UserServiceUpdateSettingsErrors[keyof UserServiceUpdateSettingsErrors];

export type UserServiceUpdateSettingsResponses = {
    /**
     * A successful response.
     */
    200: UpdateSettingsResponse;
};

export type UserServiceUpdateSettingsResponse = UserServiceUpdateSettingsResponses[keyof UserServiceUpdateSettingsResponses];

export type UserServiceApplyVerificationData = {
    body: ApplyVerificationRequest;
    path?: never;
    query?: never;
    url: '/v1/me/verification';
};

export type UserServiceApplyVerificationErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceApplyVerificationError = UserServiceApplyVerificationErrors[keyof UserServiceApplyVerificationErrors];

export type UserServiceApplyVerificationResponses = {
    /**
     * A successful response.
     */
    200: ApplyVerificationResponse;
};

export type UserServiceApplyVerificationResponse = UserServiceApplyVerificationResponses[keyof UserServiceApplyVerificationResponses];

export type PortalServiceListMinistersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 如果为 0，返回所有届部长的聚合列表？或者需要新的聚合结构
         * 建议：可以不传参数，直接返回按届分组好的数据
         */
        year?: number;
    };
    url: '/v1/ministers';
};

export type PortalServiceListMinistersErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PortalServiceListMinistersError = PortalServiceListMinistersErrors[keyof PortalServiceListMinistersErrors];

export type PortalServiceListMinistersResponses = {
    /**
     * A successful response.
     */
    200: ListMinistersResponse;
};

export type PortalServiceListMinistersResponse = PortalServiceListMinistersResponses[keyof PortalServiceListMinistersResponses];

export type MessageServiceListNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 必填：按大类拉取
         *
         * - CATEGORY_INTERACTION: 赞、收藏 (通常合并展示)
         * - CATEGORY_COMMENT: 评论、@提到 (通常合并展示)
         * - CATEGORY_FOLLOW: 新增关注
         * - CATEGORY_SYSTEM: 系统通知 (活动、公告、举报反馈)
         */
        category?: 'CATEGORY_UNSPECIFIED' | 'CATEGORY_INTERACTION' | 'CATEGORY_COMMENT' | 'CATEGORY_FOLLOW' | 'CATEGORY_SYSTEM';
        /**
         * 游标（用于无限滚动，最后一条数据的id）
         */
        'pagination.page_token'?: string;
        'pagination.need_num'?: number;
    };
    url: '/v1/notifications';
};

export type MessageServiceListNotificationsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type MessageServiceListNotificationsError = MessageServiceListNotificationsErrors[keyof MessageServiceListNotificationsErrors];

export type MessageServiceListNotificationsResponses = {
    /**
     * A successful response.
     */
    200: ListNotificationsResponse;
};

export type MessageServiceListNotificationsResponse = MessageServiceListNotificationsResponses[keyof MessageServiceListNotificationsResponses];

export type MessageServiceMarkReadData = {
    body: MarkReadRequest;
    path?: never;
    query?: never;
    url: '/v1/notifications/read';
};

export type MessageServiceMarkReadErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type MessageServiceMarkReadError = MessageServiceMarkReadErrors[keyof MessageServiceMarkReadErrors];

export type MessageServiceMarkReadResponses = {
    /**
     * A successful response.
     */
    200: MarkReadResponse;
};

export type MessageServiceMarkReadResponse = MessageServiceMarkReadResponses[keyof MessageServiceMarkReadResponses];

export type MessageServiceGetUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/notifications/unread-count';
};

export type MessageServiceGetUnreadCountErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type MessageServiceGetUnreadCountError = MessageServiceGetUnreadCountErrors[keyof MessageServiceGetUnreadCountErrors];

export type MessageServiceGetUnreadCountResponses = {
    /**
     * A successful response.
     */
    200: GetUnreadCountResponse;
};

export type MessageServiceGetUnreadCountResponse = MessageServiceGetUnreadCountResponses[keyof MessageServiceGetUnreadCountResponses];

export type ContentServiceListPostsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 帖子瀑布流类别："all"：全部, "following": 关注，“user”：用户，“self_post”：自己发布的帖子，“self_like”：自己点赞的帖子，“self_collect”：自己收藏的帖子，剩下的根据“编辑分区”中的分区id来区分。
         */
        scene?: string;
        /**
         * 刷新类型：下拉刷新（返回最新数据）/上拉加载更多（返回历史数据）
         *
         * - REFRESH_TYPE_PULL_DOWN: 下拉刷新，获取最新数据
         * - REFRESH_TYPE_PULL_UP: 上拉加载，获取历史数据
         */
        refresh_type?: 'REFRESH_TYPE_UNSPECIFIED' | 'REFRESH_TYPE_PULL_DOWN' | 'REFRESH_TYPE_PULL_UP';
        /**
         * 关键词搜索
         */
        'filter.keyword'?: string;
        /**
         * 开始时间
         */
        'filter.time_range.start_timestamp'?: string;
        /**
         * 结束时间
         */
        'filter.time_range.end_timestamp'?: string;
        /**
         * 需要返回的帖子数量
         */
        need_num?: number;
        /**
         * 排序类型："score"（分数排序）、"timestamp"（时间戳排序）
         *
         * - ORDER_TYPE_RECOMMENDED: 推荐排序
         * - ORDER_TYPE_LATEST: 最新排序
         * - ORDER_TYPE_HOT: 热门排序
         */
        order_type?: 'ORDER_TYPE_UNSPECIFIED' | 'ORDER_TYPE_RECOMMENDED' | 'ORDER_TYPE_LATEST' | 'ORDER_TYPE_HOT';
        /**
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数，order_type=ORDER_TYPE_RECOMMENDED 或 order_type=ORDER_TYPE_HOT
         */
        cursor_score?: string;
        /**
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间，order_type=ORDER_TYPE_LATEST
         */
        cursor_timestamp?: string;
    };
    url: '/v1/posts';
};

export type ContentServiceListPostsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ContentServiceListPostsError = ContentServiceListPostsErrors[keyof ContentServiceListPostsErrors];

export type ContentServiceListPostsResponses = {
    /**
     * A successful response.
     */
    200: ListPostsResponse;
};

export type ContentServiceListPostsResponse = ContentServiceListPostsResponses[keyof ContentServiceListPostsResponses];

export type ContentServiceCreatePostData = {
    body: CreatePostRequest;
    path?: never;
    query?: never;
    url: '/v1/posts';
};

export type ContentServiceCreatePostErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ContentServiceCreatePostError = ContentServiceCreatePostErrors[keyof ContentServiceCreatePostErrors];

export type ContentServiceCreatePostResponses = {
    /**
     * A successful response.
     */
    200: CreatePostResponse;
};

export type ContentServiceCreatePostResponse = ContentServiceCreatePostResponses[keyof ContentServiceCreatePostResponses];

export type ContentServiceDeletePostData = {
    body?: never;
    path: {
        post_id: string;
    };
    query?: never;
    url: '/v1/posts/{post_id}';
};

export type ContentServiceDeletePostErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ContentServiceDeletePostError = ContentServiceDeletePostErrors[keyof ContentServiceDeletePostErrors];

export type ContentServiceDeletePostResponses = {
    /**
     * A successful response.
     */
    200: DeletePostResponse;
};

export type ContentServiceDeletePostResponse = ContentServiceDeletePostResponses[keyof ContentServiceDeletePostResponses];

export type ContentServiceGetPostData = {
    body?: never;
    path: {
        post_id: string;
    };
    query?: never;
    url: '/v1/posts/{post_id}';
};

export type ContentServiceGetPostErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ContentServiceGetPostError = ContentServiceGetPostErrors[keyof ContentServiceGetPostErrors];

export type ContentServiceGetPostResponses = {
    /**
     * A successful response.
     */
    200: GetPostResponse;
};

export type ContentServiceGetPostResponse = ContentServiceGetPostResponses[keyof ContentServiceGetPostResponses];

export type CommentServiceListCommentsData = {
    body?: never;
    path: {
        /**
         * 必须：帖子ID
         */
        post_id: string;
    };
    query?: {
        /**
         * 可选：如果不传(或空)，则获取该帖子的一级评论列表
         * 如果传了 comment_id，则获取该评论下的子评论列表 (展开回复)
         */
        root_id?: string;
        /**
         *  - SORT_HOT: 热度 (点赞+回复权重)
         * - SORT_NEW: 最新 (时间倒序)
         * - SORT_OLD: 最早 (时间正序，常用于楼中楼)
         */
        sort?: 'SORT_UNSPECIFIED' | 'SORT_HOT' | 'SORT_NEW' | 'SORT_OLD';
        /**
         * 游标（用于无限滚动，最后一条数据的id）
         */
        'pagination.page_token'?: string;
        'pagination.need_num'?: number;
    };
    url: '/v1/posts/{post_id}/comments';
};

export type CommentServiceListCommentsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type CommentServiceListCommentsError = CommentServiceListCommentsErrors[keyof CommentServiceListCommentsErrors];

export type CommentServiceListCommentsResponses = {
    /**
     * A successful response.
     */
    200: ListCommentsResponse;
};

export type CommentServiceListCommentsResponse = CommentServiceListCommentsResponses[keyof CommentServiceListCommentsResponses];

export type CommentServiceCreateCommentData = {
    body: CommentServiceCreateCommentBody;
    path: {
        post_id: string;
    };
    query?: never;
    url: '/v1/posts/{post_id}/comments';
};

export type CommentServiceCreateCommentErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type CommentServiceCreateCommentError = CommentServiceCreateCommentErrors[keyof CommentServiceCreateCommentErrors];

export type CommentServiceCreateCommentResponses = {
    /**
     * A successful response.
     */
    200: CreateCommentResponse;
};

export type CommentServiceCreateCommentResponse = CommentServiceCreateCommentResponses[keyof CommentServiceCreateCommentResponses];

export type ResourceServiceGetUploadTokensData = {
    body: GetUploadTokensRequest;
    path?: never;
    query?: never;
    url: '/v1/resources/upload-tokens';
};

export type ResourceServiceGetUploadTokensErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ResourceServiceGetUploadTokensError = ResourceServiceGetUploadTokensErrors[keyof ResourceServiceGetUploadTokensErrors];

export type ResourceServiceGetUploadTokensResponses = {
    /**
     * A successful response.
     */
    200: GetUploadTokensResponse;
};

export type ResourceServiceGetUploadTokensResponse = ResourceServiceGetUploadTokensResponses[keyof ResourceServiceGetUploadTokensResponses];

export type PortalServiceGetSiteConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/site/config';
};

export type PortalServiceGetSiteConfigErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PortalServiceGetSiteConfigError = PortalServiceGetSiteConfigErrors[keyof PortalServiceGetSiteConfigErrors];

export type PortalServiceGetSiteConfigResponses = {
    /**
     * A successful response.
     */
    200: GetSiteConfigResponse;
};

export type PortalServiceGetSiteConfigResponse = PortalServiceGetSiteConfigResponses[keyof PortalServiceGetSiteConfigResponses];

export type PortalServiceListSponsorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/sponsors';
};

export type PortalServiceListSponsorsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PortalServiceListSponsorsError = PortalServiceListSponsorsErrors[keyof PortalServiceListSponsorsErrors];

export type PortalServiceListSponsorsResponses = {
    /**
     * A successful response.
     */
    200: ListSponsorsResponse;
};

export type PortalServiceListSponsorsResponse = PortalServiceListSponsorsResponses[keyof PortalServiceListSponsorsResponses];

export type PortalServiceListStaffData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/staff';
};

export type PortalServiceListStaffErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PortalServiceListStaffError = PortalServiceListStaffErrors[keyof PortalServiceListStaffErrors];

export type PortalServiceListStaffResponses = {
    /**
     * A successful response.
     */
    200: ListStaffResponse;
};

export type PortalServiceListStaffResponse = PortalServiceListStaffResponses[keyof PortalServiceListStaffResponses];

export type PortalServiceListHomeTrendingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 限制数量，如 6 条
         */
        limit?: number;
    };
    url: '/v1/trending';
};

export type PortalServiceListHomeTrendingErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PortalServiceListHomeTrendingError = PortalServiceListHomeTrendingErrors[keyof PortalServiceListHomeTrendingErrors];

export type PortalServiceListHomeTrendingResponses = {
    /**
     * A successful response.
     */
    200: ListHomeTrendingResponse;
};

export type PortalServiceListHomeTrendingResponse = PortalServiceListHomeTrendingResponses[keyof PortalServiceListHomeTrendingResponses];

export type UserServiceGetUsersData = {
    body?: never;
    path?: never;
    query?: {
        user_ids?: Array<string>;
    };
    url: '/v1/users';
};

export type UserServiceGetUsersErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceGetUsersError = UserServiceGetUsersErrors[keyof UserServiceGetUsersErrors];

export type UserServiceGetUsersResponses = {
    /**
     * A successful response.
     */
    200: GetUsersResponse;
};

export type UserServiceGetUsersResponse = UserServiceGetUsersResponses[keyof UserServiceGetUsersResponses];

export type UserServiceListRelationshipsData = {
    body?: never;
    path: {
        /**
         * 查看谁的关系
         */
        user_id: string;
    };
    query?: {
        /**
         *  - RELATION_TYPE_FOLLOWING: 关注的人
         * - RELATION_TYPE_FOLLOWERS: 粉丝
         * - RELATION_TYPE_MUTUAL_FOLLOWERS: 互相关注
         */
        type?: 'RELATION_TYPE_FOLLOWING' | 'RELATION_TYPE_FOLLOWERS' | 'RELATION_TYPE_MUTUAL_FOLLOWERS';
        /**
         * 游标（用于无限滚动，最后一条数据的id）
         */
        'pagination.page_token'?: string;
        'pagination.need_num'?: number;
        /**
         * 可选：按昵称/备注/QQ号搜索过滤
         */
        keyword?: string;
    };
    url: '/v1/users/{user_id}/relationships';
};

export type UserServiceListRelationshipsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceListRelationshipsError = UserServiceListRelationshipsErrors[keyof UserServiceListRelationshipsErrors];

export type UserServiceListRelationshipsResponses = {
    /**
     * A successful response.
     */
    200: ListRelationshipsResponse;
};

export type UserServiceListRelationshipsResponse = UserServiceListRelationshipsResponses[keyof UserServiceListRelationshipsResponses];
